---
title: "Go 1.21 リリース連載 contextパッケージに追加されるWithoutCancelでクライアントとの切断に備えてみる"
date: 2023/08/03 00:00:00
postid: a
tag:
  - Go
  - Go1.21
  - context
category:
  - Programming
thumbnail: /images/20230803a/thumbnail.png
author: 藤井亮佑
lede: "Go 1.21 連載の記事を書きます。"
---
## はじめに

こんにちは。TIG DX ユニット所属、金欠コンサルタントの藤井です。先日、Google Pixel 7aを購入しました。これまでiPhone 7 Plusを使っていたので、使用スマホの時代が7年ほど進みました。Googleは検索エンジンからAI、スマホまで作っていてすごいですね。

ということで今回は、Google発のプログラミング言語であるところのGoの1.21がリリースされることを記念した、[Go 1.21 連載](/articles/20230731a/) の記事を書きます。

本記事では、いくつか変更の入った、[context](https://pkg.go.dev/context@master)パッケージについて記載していきます。

contextそのものについては、フューチャー技術ブログにおいても数多く解説されていますので、詳細な説明は割愛します。数例記載しますので、ぜひご覧ください。

- 辻さんの[Go1.14のRelease Partyに登壇しました](https://future-architect.github.io/articles/20200325/)
    - 記事の本質ではないですが、context自体の役割など、基礎情報が記載されています。
- 伊藤さんの[「Contextを完全に理解する」というテーマでGo Conference 2021 Autumnに登壇しました](https://future-architect.github.io/articles/20211119a/)
    - context自体の実装について記載されています。
- 真野さんの[Go1.20リリース連載 contextパッケージのWithCancelCauseとCause](https://future-architect.github.io/articles/20230125a/)
    - 1つ前の1.20においてcontextに追加された関数についての解説記事です。

## 変更点概要

Minor changes to the libraryとして、計4点の更新が加えられています。

- [WithoutCancel](https://tip.golang.org/pkg/context/#WithoutCancel)の追加
    - 親子`context`間のキャンセルの伝播を切断し、親の`context`がキャンセル/タイムアウトした場合にも、自身の`context`がキャンセルされない子`context`を作成できるようになりました。
    - なお、`WithoutCancel`という名前ではありますが、文字通りのキャンセルのみではなく、タイムアウトについても伝播されなくなります。
      - contextに設定した変数（ロガーやトレースID）などを利用したいけど、キャンセルは利用したくないなどの場合に利用できるとのことです
- [WithDeadlineCause](https://tip.golang.org/pkg/context/#WithDeadlineCause)および[WithTimeoutCause](https://tip.golang.org/pkg/context/#WithTimeoutCause)の追加
    - 先述の[Go1.20リリース連載 contextパッケージのWithCancelCauseとCause](https://future-architect.github.io/articles/20230125a/)にて解説されている、`WithCancelCause`の`Deadline`と`Timeout`版です。
- [AfterFunc](https://tip.golang.org/pkg/context/#AfterFunc)の追加
    - contextがキャンセル/タイムアウトした後に実行する処理を登録するための関数です。[timeパッケージのAfterFunc](https://pkg.go.dev/time#AfterFunc)と使い方はほとんど同じですが、使い道は大きく異なり、Exampleにあるように（当然ですが）contextに主軸をおいた物となっており、以下がExampleとして挙げられています。
        - 直感的な使い方として、[sync.Condの待ちを中断](https://pkg.go.dev/context@master#example-AfterFunc-Cond)・[net.Connの接続を遮断](https://pkg.go.dev/context@master#example-AfterFunc-Connection)等の、不要な処理を止める使い道
        - [複数のcontextをマージ](https://pkg.go.dev/context@master#example-AfterFunc-Merge)して、いずれかの`context`がキャンセルされると、マージ後の`context`もキャンセルされる、新たな`context`を作成する使い道
            - [proposal](https://github.com/golang/go/issues/57928)によると、この使い道が発端のようです。`context`の持ち方自体に新しい手法が生まれるので、アイデア次第で化けそうです。
- 最適化の結果として、`context`どうしを比較したときの振る舞いに変更が発生した
    - 比較の仕方によって、`context`どうしの比較結果が1.20以前と異なる場合があるようです。ただし、今までもこれからも、`context`どうしの比較は明確に定義されていないため、いずれにせよ`context`どうしの比較結果に依存した実装は危険かもしれません。
    - [こちらのissue](https://github.com/golang/go/issues/60978)で指摘が挙がったようです。

個人的には`WithoutCancel`と`AfterFunc`がインパクト大きめのアップデートかなと思います。本記事では`WithoutCancel`に着目して、実際に試してみた結果を記載していきます。

## 試す内容

`context`を引き回すケースとして、WEB APIサーバというのは代表例の一つかと思います。
私の所属しているプロジェクトでも、リクエストスコープごとに`context`を引き回しています。
そこで、こんなコードを考えてみます。

```Go
package main

import (
	"fmt"
	"net/http"
	"time"
)

func handler(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	url := "http://localhost:8080/heavy"
	req, err := http.NewRequestWithContext(ctx, "POST", url, nil)
	if err != nil {
		return
	}

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer resp.Body.Close()
    fmt.Println("COMPLETE!!")
}

func heavyHandler(w http.ResponseWriter, r *http.Request) {
	time.Sleep(10 * time.Second)
	return
}

func main() {
	http.HandleFunc("/api", handler)
	http.HandleFunc("/heavy", heavyHandler)
	http.ListenAndServe(":8080", nil)
}
```

`/api`というエンドポイントにリクエストを受けると、`http.Request`から受け取った`context`を引き回し、そのまま違うAPI `/heavy` にリクエストを送っています。
`/heavy`はその名の通り重い処理を担当しているとし、常に10秒の処理時間がかかるようにしています。
今回は極めて簡易的に作っているため、自身に対してリクエストを送っています（さらにこちらでは`context`未使用）が、異なるサーバであっても本質には影響しません。

さて、このサーバに対して`CURL`等で実際にリクエストを送ってから10秒待ってみると、特にレスポンス等も定義していないため、10秒後にログに`COMPLETE!!`と出る以外全く何も起こりません。
しかし、耐えかねて`CURL`に`SIGINT`を送ってみたところ

```bash
$ go run .
Post "http://localhost:8080/heavy": context canceled
```

怒られてしまいました。どうやらどこかで`context`がキャンセルされてしまったようです。
[net/httpパッケージの仕様](https://pkg.go.dev/net/http#Request.Context)を見てみると、クライアントとの接続が切断されると、`context`はキャンセルされる、とあり、これの仕業のようです。
サービスによってはクライアントの通信環境が不安定（スマートフォンがメインターゲットで、トンネルに入るたびに圏外になるなど）な場合もあり、クライアントとの接続状況には十分な考慮が必要です。

今回の例では、実質的には何の処理も行っていないため、クライアントとの切断により`context`がキャンセルされても困りませんが、実際には結構困る場面があります。
[proposal](https://github.com/golang/go/issues/40221)では、以下が例として挙げられています。

- rollback/cleanupの処理はトリガーイベント（HTTPリクエスト等）のキャンセル状況によらず継続する必要がある
- トリガーイベント（HTTPリクエスト等）の方が早く処理が完了した場合にも、処理を完遂したい

上記以外にも、システム間連携が多いことなどを原因として、リクエストからレスポンスまでの処理においてAtomicityが担保されていない場合、`context`がキャンセルされるタイミングによってはデータ不整合が発生する可能性があります。
システム間連携も含めてAtomicであることが望ましいのは間違いないのですが、規模や要件によって、常に理想の設計ができるとは限りません。

<img src="/images/20230803a/image.png" alt="image.png" width="768" height="549" loading="lazy">

ということで、今回は`WithoutCancel`を用いて、クライアントとの接続が切断した場合も、（サーバ側で問題が起きない限り）処理を継続するよう、改造してみます。

## 試してみた

対応内容は極めて単純で、`http.Request`から`context`を受け取る箇所を、以下のように変更し、`WithoutCancel`で新しい`context`を作成するだけです。
必要に応じて`WithCancel`や`WithTimeout`等を重ねて使ってももちろんOKです。

```Go
ctx := context.WithoutCancel(r.Context())
```

この状態で再度`CURL`を叩き、すぐさま切断すると…

```bash
$ go run .
COMPLETE!!
```

親`context`はキャンセルされているにも関わらず、10秒後に正しく処理が完了したようです。
これで、クライアントとの接続状況に左右されず、処理を完遂できるようになりました。

## おわりに

Go 1.21で`context`パッケージに追加される`WithoutCancel`を試してみました。
伝播してほしくない親のキャンセルを極めて簡単に無視できるようになった、という話なのですが、しかしながら問答無用で無視して良いものなのか、というところは慎重に考える必要があるかと思います。
キャンセルやタイムアウトの伝播は、それこそAtomicityやConsistencyを担保するために非常に有用なものであり、無闇に伝播を切断すると、実質的に`context`が大量に生まれてしまい、非常に難解なものになるリスクがあります。
[proposalへのコメント](https://github.com/golang/go/issues/40221#issuecomment-658573098)にも、`context`の単なるKVSとしての利用を促進しかねない、といった旨の危惧が記載されています。
導入前に、改めて「本当にこの時点で親`context`のキャンセルは無視して良いのか？」を精査するべきかと思います。

明日は谷村さんの記事で、とうとうGoに`min`/`max`関数が追加されるようです。お楽しみに！
